language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

jobs:
  allow_failures:
  - php: nightly

script:
  # Validate composer.json file.
  - composer validate
  # Install
  - composer install --ignore-platform-reqs
