language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  #- nightly = 8.0

script:
  # Update composer to latest version.
  - composer self-update || true
  # For faster installing
  - composer global require hirak/prestissimo
  # Validate composer.json file.
  - composer validate
  # Install
  - composer install
